### PR TITLE
Feature 1 completed in 16 minutes

### PR DESCRIPTION
**Pull request by a99jafari**

### CODE REVIEW

**Review by sassanh — CHANGES_REQUESTED** [review]
Looks very good, I added a few minor comments

**Comment by a99jafari** [comment]
Thank you for your attention, the tips and details you wrote.
Do I need to make the changes you mentioned on a new branch?

**Comment by sassanh** [comment]
@a99jafari No, we should resolve them in this branch.
(BTW, please do not close any pull request from now on, we want to practice updating pull requests instead of recreating them)

**Review by sassanh — APPROVED** [review]
Looks good to merge

**Pull request merged**
